prog:main_init.o init_afficher.o
	gcc main_init.o init_afficher.o -o prog -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
fonctions.o:init_afficher.c
	gcc -c init-afficher.c -g
main.o:main.c
	gcc -c main_init.c -g
	
